"""WebSocket clients and models for OKC real-time APIs."""

from ..models.breaks import (
    AuthMessage,
    BreakLineData,
    BreakUser,
    DischargeUser,
    PageData,
    QueueOperator,
    SimpleBreakLineData,
    SimplePageData,
    UserBreaks,
)
from ..models.lines import (
    Agent,
    Agents,
    AssignAgent,
    AuthRoles,
    BossInfo,
    BreakAgent,
    ChatCapacity,
    CiscoAgent,
    CiscoAgents,
    CiscoAssignment,
    CiscoQueueInfo,
    CiscoRawData,
    CitiesInProcess,
    CitiesStatuses,
    CityInQueue,
    CityStatus,
    CityWithChats,
    Incident,
    IncidentStat,
    LastMessage,
    LineDuty,
    NotReadyAgent,
    QueueInfo,
    RawData,
    RawIncidents,
    ReadyAgent,
    WaitingChats,
)

__all__ = [
    "QueueInfo",
    "ChatCapacity",
    "WaitingChats",
    "Agent",
    "ReadyAgent",
    "NotReadyAgent",
    "AssignAgent",
    "BreakAgent",
    "Agents",
    "LineDuty",
    "LastMessage",
    "CityInQueue",
    "CityWithChats",
    "CitiesInProcess",
    "CityStatus",
    "CitiesStatuses",
    "RawData",
    "Incident",
    "IncidentStat",
    "RawIncidents",
    "AuthRoles",
    # Cisco models for ntp1/ntp2 lines
    "CiscoAgent",
    "CiscoAgents",
    "CiscoAssignment",
    "CiscoQueueInfo",
    "CiscoRawData",
    "BossInfo",
    # Breaks models
    "BreakLineData",
    "BreakUser",
    "DischargeUser",
    "PageData",
    "QueueOperator",
    "SimpleBreakLineData",
    "SimplePageData",
    "AuthMessage",
    "UserBreaks",
]
